# SPDX-FileCopyrightText: 2026 Sephyi <me@sephy.io>
# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0

FROM ubuntu:24.04
RUN apt-get update && apt-get install -y bind9 bind9-utils && rm -rf /var/lib/apt/lists/*
COPY named.conf /etc/bind/named.conf
COPY zones/ /var/lib/bind/
RUN chown -R bind:bind /var/lib/bind
EXPOSE 53/udp 53/tcp 953/tcp 8053/tcp
CMD ["/usr/sbin/named", "-g", "-c", "/etc/bind/named.conf", "-u", "bind"]
